spring.application.name=TinyBook
spring.datasource.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:8080/TinyBook
spring.datasource.username= postgres
spring.datasource.password= 04032003
spring.jpa.hibernate.ddl=true
spring.jpa.generate-ddl-auto=update
spring.jpa.show-sql=true
server.port=8081